### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by techwiz37** [potatonc/ScriptAutoInstallPotato#1]
ini hanya ssh & ovpn?

**Comment by potatonc** [comment]
vmess, vless, trojan, wireguard, l2tp dkk.

**Comment by potatonc** [comment]
> ini hanya ssh & ovpn?

vmess, vless, trojan, wireguard, l2tp dkk.

**Comment by techwiz37** [comment]
comandnya gmn. ush ku install ku ketik menu gk bsa
